name: {{cookiecutter.project_name.lower().replace(' ', '_')}}
channels:
  - default
  - conda-forge
dependencies:
  - ipykernel
  - numpy
  - nbconvert
  - nbformat
  - pip
  - pandas
  - pytest
  - pytest-cookies
  - pytest-cov
  - pip:
    - fastapi
    - flake8
    - m2r
    - pyjstat
    - sphinx
    - uvicorn

